#!/bin/bash
yum install -y httpd mysql-server 
rpm -qa | grep "nodejs"
if [ $? -eq 0 ];
then
        echo "NODEJS SERVER IS INSTALLED"

else
        echo "INSTALLING NODEJS SERVER"
	curl --silent --location https://rpm.nodesource.com/setup_11.x | sudo bash -
	yum install -y nodejs npm
	npm install pm2 -g
fi
